---
# tasks file for add_rule_sudoers

- name: Ensure sudoers.d directory exists
  file:
    path: /etc/sudoers.d
    state: directory
    mode: '0750'

- name: Include task mod_lineinfile.yml
  include_tasks: tasks/mod_lineinfile.yml
