---
# tasks file for add_rule_sudoers

- name: Ensure sudoers.d directory exists
  file:
    path: /etc/sudoers.d
    state: directory
    mode: '0750'

- name: Include task done_using_template_file.yml
  include_tasks: tasks/done_using_template_file.yml
