---
- name: Add sudoers rule for each user
  vars:
    sudo_users_uniq: "{{ sudo_users | unique }}"
    sudo_commands_uniq: "{{ sudo_commands | unique }}"
    on_skipped_msg: |
      Vars:
      sudo_users: {{ sudo_users_uniq }}
      sudo_commands:{{ sudo_commands_uniq }}
    on_skipped_msg_color: "yellow"

  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ item | replace('.','_') | replace('%','') }}"
    create: true
    search_string: "{{ item }} ALL=({{ run_as }}) {{ (nopasswd == true) | ternary('NOPASSWD:','') }} {{ sudo_commands_uniq | join(', ') }}"
    line: "{{ item }} ALL=({{ run_as }}) {{ (nopasswd == true) | ternary('NOPASSWD:','') }} {{ sudo_commands_uniq | join(', ') }}"
    mode: '0440'

  loop: "{{ sudo_users_uniq }}"
  when: (sudo_users is defined and sudo_users | length > 0) and
    (sudo_commands is defined and sudo_commands | length > 0)
