---
- name: Gather the system facts
  ansible.builtin.setup:
    gather_subset:
      - hardware
      - network
      - distribution

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Get size installed RAM
  ansible.builtin.shell: |
    dmidecode -t memory | grep 'Size:' | grep -v 'No Module Installed' \
    | awk '{sum+=$2} END {print sum}'
  become: true
  register: ghi_total_installed_ram
  changed_when: false

- name: Get the name of the physical system disk
  ansible.builtin.shell: |
    lsblk -lns -o NAME,TYPE $(findmnt -n -o SOURCE /) \
    | awk '$2 == "disk" {print $1; exit}'
  register: ghi_system_disk_name
  changed_when: false

- name: Save host info
  ansible.builtin.set_fact:
    ghi_collected_host_info:
      hostname: "{{ inventory_hostname }}"
      ip: "{{ ansible_default_ipv4.address | default('N/A') }}"
      os: "{{ ansible_distribution | default('N/A') }}"
      os_version: "{{ ansible_distribution_version | default('N/A') }}"
      cpu: "{{ ansible_processor_vcpus | default('N/A') }}"
      ram: "{{ ghi_total_installed_ram.stdout | default('N/A') }}"
      packages: >-
        {{ ansible_facts.packages
          | dict2items
          | selectattr('key', 'match', ghi_package_name_regex | join('|'))
          | list }}
      disks: >-
        {{ ansible_devices
          | dict2items
          | rejectattr('key', 'match', '^(fd|loop|sr|ram|dm-|md|zram)')
          | items2dict }}
      system_disk_name: "{{ ghi_system_disk_name.stdout | default('N/A') }}"
