---
- name: Installing packages via APT
  ansible.builtin.apt:
    name: "{{ ddhcp_install_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_pkg_mgr == "apt_rpm"

- name: Installing packages via DNF/YUM
  ansible.builtin.dnf:
    name: "{{ ddhcp_install_packages }}"
    state: present
    update_cache: yes
  when: >
    ansible_pkg_mgr == "dnf"
    or ansible_pkg_mgr == "yum"

- name: Install packages
  ansible.builtin.package:
    name: "{{ ddhcp_install_packages }}"
    state: present
  when:
    - ansible_pkg_mgr != "apt_rpm"
    - ansible_pkg_mgr != "dnf"
    - ansible_pkg_mgr != "yum"
