---
- name: Remove NTPD
  ansible.builtin.package:
    name: ntp
    state: absent

- name: Stop Systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: false
    state: stopped
  register: cntpc_result_stop_systemd_timesyncd
  failed_when:
    - cntpc_result_stop_systemd_timesyncd.failed == true
    - '"Could not find the requested service systemd-timesyncd" not in cntpc_result_stop_systemd_timesyncd.msg'

- name: Install Chrony
  ansible.builtin.package:
    name: chrony
    state: present
  register: cntpc_result_install_chrony

- name: Set chrony.conf
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0640
  register: cntpc_result_set_chrony

- name: Enable and start chronyd.service
  ansible.builtin.service:
    name: chronyd
    enabled: true
    state: started

- name: Restart chronyd
  ansible.builtin.service:
    name: chronyd
    daemon-reload: true
    state: restarted
  when: >
    cntpc_result_install_chrony.changed == true or
    cntpc_result_set_chrony.changed == true
