---
- name: Check if the DC already exists
  command: samba-tool domain info 127.0.0.1
  register: dadl_result_check_dc
  ignore_errors: true

- name: DC already exists
  fail:
    msg: DC already exists
  when: dadl_result_check_dc.rc == 0

- block:
  - name: Backup /etc/samba/smb.conf to /etc/samba/smb.conf.bkp
    copy:
      src: /etc/samba/smb.conf
      dest: /etc/samba/smb.conf.bkp
      remote_src: true
      force: true

  - name: Remove file /etc/samba/smb.conf
    ansible.builtin.file:
      path: /etc/samba/smb.conf
      state: absent

  - name: Create domain
    command: >
      samba-tool domain provision
        --realm={{ dadl_domain_name }}
        --domain={{ dadl_domain_name.split('.')[0] }}
        --adminpass={{ dadl_adminpass }}
        --dns-backend=BIND9_DLZ
        --option="ad dc functional level = {{ dadl_domain_function_level }}"
        --server-role=dc
        --function-level={{ dadl_domain_function_level }}
        --base-schema={{ dadl_base_schema }}
    register: dadl_result_create_domain

  - name: Copy /var/lib/samba/private/krb5.conf to /etc/krb5.conf
    copy:
      src: /var/lib/samba/private/krb5.conf
      dest: /etc/krb5.conf
      remote_src: true
      force: true
      backup: true

  - name: Start services samba and bind
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: true
      state: started
    loop:
      - samba
      - bind

  when: dadl_result_check_dc.failed == true
