---
- name: kinit
  args:
    executable: /usr/bin/expect
  ansible.builtin.shell: |
    spawn kinit {{ dald_admin_AD_username }}@{{ dald_domain_name | upper }}
    expect -exact "Password for {{ dald_admin_AD_username }}@{{ dald_domain_name | upper }}:"
    send -- "{{ dald_admin_AD_pass }}\n"
    expect eof
  no_log: true

- name: klist
  ansible.builtin.command: klist
  register: dald_result_klist_ticket

- debug:
    var: dald_result_klist_ticket

- debug:
    msg: "{{ dald_result_klist_ticket.stdout_lines[0].split(' ')[2] }}"
