---
- name: Setting up an SSH connection between domain controllers
  ansible.builtin.import_tasks: setting_ssh_connection.yml

- name: Execute on {{ daldc_ip_primary_dc }}
  delegate_to: "{{ daldc_ip_primary_dc }}"
  block:
    - name: Check file existence idmap.ldb.
      ansible.builtin.stat:
        path: /var/lib/samba/private/idmap.ldb.bak
      register: daldc_result_file_idmap

    - name: Backup /var/lib/samba/private/idmap.ldb to /var/lib/samba/private/idmap.ldb.bak
      ansible.builtin.command: tdbbackup -s .bak /var/lib/samba/private/idmap.ldb
      when: not daldc_result_file_idmap.stat.exists

    - name: Creates a cron file under /etc/cron.d/idmap
      ansible.builtin.cron:
        name: Backup /var/lib/samba/private/idmap.ldb
        hour: "3"
        user: root
        job: >
          "rm -f /var/lib/samba/private/idmap.ldb.bak
          && tdbbackup -s .bak /var/lib/samba/private/idmap.ldb >/dev/null 2>&1"
        cron_file: idmap

    - name: Install osync
      ansible.builtin.package:
        name: osync
        state: present

    - name: Create config sync SysVol
      ansible.builtin.template:
        src: templates/sync.conf.j2
        dest: "/etc/osync/sync_{{ inventory_hostname }}.conf"
        owner: root
        group: root
        mode: '0644'

    - name: Creates a cron file under /etc/cron.d/sysvol
      ansible.builtin.lineinfile:
        path: /etc/cron.d/sysvol
        search_string: "/usr/bin/osync.sh /etc/osync/sync_{{ inventory_hostname }}.conf"
        line: "*/5 * * * * root /usr/bin/osync.sh /etc/osync/sync_{{ inventory_hostname }}.conf --silent"
        create: true
        owner: root
        group: root
        mode: '0644'

    - name: Sync SysVol
      ansible.builtin.command: /usr/bin/osync.sh /etc/osync/sync_{{ inventory_hostname }}.conf
      ignore_errors: true

- name: Create /etc/cron.d/idmap
  ansible.builtin.cron:
    name: Sync /var/lib/samba/private/idmap.ldb
    minute: "15"
    hour: "4"
    user: root
    job: >
      rsync -a {{ daldc_ip_primary_dc }}:/var/lib/samba/private/idmap.ldb.bak /var/lib/samba/private/idmap.ldb
      && net cache flush
      && if ! samba-tool ntacl sysvolcheck; then samba-tool ntacl sysvolreset; fi
      && systemctl restart samba.service >/dev/null 2>&1
    cron_file: idmap

- name: Sync idmap.ldb
  ansible.builtin.shell: >
    rsync -a {{ daldc_ip_primary_dc }}:/var/lib/samba/private/idmap.ldb.bak /var/lib/samba/private/idmap.ldb
    && net cache flush
    && if ! samba-tool ntacl sysvolcheck; then samba-tool ntacl sysvolreset; fi
    && systemctl restart samba.service
