---
- name: Check if the DC already exists
  ansible.builtin.command: samba-tool domain info 127.0.0.1
  register: daldc_result_check_dc
  ignore_errors: true

- name: Check file existence /etc/samba/smb.conf
  ansible.builtin.stat:
    path: /etc/samba/smb.conf
  register: daldc_result_file_smb

- name: Backup /etc/samba/smb.conf to /etc/samba/smb.conf.bak
  ansible.builtin.copy:
    src: /etc/samba/smb.conf
    dest: /etc/samba/smb.conf.bak
    remote_src: true
    force: true
  when: daldc_result_file_smb.stat.exists

- name: Deploy DC
  block:
    # Обязательно удаляем /etc/samba/smb.conf
    - name: Remove file /etc/samba/smb.conf
      ansible.builtin.file:
        path: /etc/samba/smb.conf
        state: absent
      when: daldc_result_file_smb.stat.exists

    - name: Create primary DC
      include_tasks: create_primary_dc.yml
      when: daldc_create_domain | bool == true

    - name: Join secondary DC to domain
      include_tasks: join_secondary_dc_to_domain.yml
      when: daldc_create_domain | bool == false

  when: daldc_result_check_dc.rc != 0

- name: Set /etc/samba/smb.conf
  ansible.builtin.template:
    src: templates/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'

- name: Set /etc/krb5.conf
  ansible.builtin.template:
    src: templates/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'

- name: Start services samba and bind
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - samba
    - bind

- name: Enable keytab usage
  ansible.builtin.import_tasks: krb5_keytab.yml
