---
- name: Check input values
  ansible.builtin.import_tasks: check_input_values.yml
  tags: daldc_check_input_values

- name: Configure host
  ansible.builtin.import_tasks: configure_host.yml
  tags: daldc_configure_host

- name: Install packages
  ansible.builtin.import_tasks: install_packages.yml
  tags:
    - daldc_install_packages
    - daldc_configure_replication

- name: Stop services
  ansible.builtin.import_tasks: stop_services.yml
  tags: daldc_stop_services

- name: Configure Bind
  ansible.builtin.import_tasks: configure_bind.yml
  tags: daldc_configure_bind

- name: Create domain controller
  ansible.builtin.import_tasks: create_domain_controller.yml
  tags: daldc_create_DC

- name: Configure replication
  ansible.builtin.include_tasks: configure_replication.yml
  when: daldc_create_domain | bool == false
  tags: daldc_configure_replication
