---
- name: Check the variable dald_admin_AD_pass
  ansible.builtin.assert:
    that:
      - cli_admin_AD_pass | length > 0
    fail_msg: The variable is empty!
    quiet: true

- name: Checking password matches
  ansible.builtin.assert:
    that:
      - cli_admin_AD_pass == cli_admin_AD_pass_retype
    fail_msg: Sorry, passwords do not match.
    quiet: true

- name: Configure host
  import_tasks: configure_host.yml
  tags: dald_configure_host

- name: Install packages
  import_tasks: install_packages.yml
  tags: dald_install_packages

- name: Stop services
  import_tasks: stop_services.yml
  tags: dald_stop_services

- name: Configure Bind
  import_tasks: configure_bind.yml
  tags: dald_configure_bind

- name: Create domain
  import_tasks: create_domain.yml
  tags: dald_create_domain
